#!/usr/bin/env python3
"""Issue #3134 (repair round): the discoverability half of `amends:`.

Two mechanisms, both fails-closed, both required:

  1. A generated, cross-cutting index (`INDEX_PATH`) -- a supplementary
     "what in this tree has an open correction" summary, same
     `docs/specs/` bucket / shape as `gates/spec_index.py`.
  2. A backlink written directly into each amended target, by the
     LANDING step (never the correcting session -- see
     `amends_backlink.py`'s module docstring for why that split does not
     relax board-gate's write-set isolation). `write_backlinks()` /
     `--apply-backlinks` performs it; `check()`'s `missing_backlinks`
     reasons refuse to let an `amends:` edge land unlinked.

The #3134 repair round's independent verification found the first
delivery (index only) Absent: it redefined "reaching A" as "consulting
the index," not "opening A" -- a reader who does not already know the
index exists has no path to the correction from A's own content. (2) is
the fix; (1) stays as a secondary, cross-cutting view.

  python3 gates/amends_index.py [<repo root>]                    # check mode (CI)
  python3 gates/amends_index.py [<repo root>] --update            # regenerate the index
  python3 gates/amends_index.py [<repo root>] --apply-backlinks   # landing step: write backlinks
  exit 0 pass (or requested action done) / 1 blocked
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import amends  # noqa: E402
import amends_backlink  # noqa: E402

INDEX_PATH = "docs/specs/amends-index.md"
_RECORD_GLOB = "docs/issue-*/reports/**/*.md"

_HEADER = """# Amends index (generated -- issue #3134)

Every `amends:` edge in the tree, regenerated by
`python3 gates/amends_index.py --update` and checked for drift by
`python3 gates/amends_index.py` (no `--update`). This is a SUPPLEMENTARY
cross-cutting view -- "what in this tree has an open correction" -- not
the primary discoverability mechanism: the primary mechanism is the
backlink the landing step writes directly into each amended target's own
content (`python3 gates/amends_index.py --apply-backlinks`; see
`amends_backlink.py`'s module docstring for why the correcting session
cannot write it itself). A reader who opens a record directly sees the
backlink there; this index is for the standing question "what's
outstanding right now," across every record at once.

A target#section pair absent from this table has no outstanding
amendment recorded in the tree. `broken` / `missing_section` /
`conflicts` / `cycles` entries are edges that failed to resolve
closed -- see `amends.py::resolve_amendments()` -- and are listed so a
human can act on them; none of them counts as a live amendment.

## Amended sections

| target#section | amending record | reason |
|---|---|---|
{rows}

## Unresolved edges

{unresolved}
"""


def _load_records(repo: Path) -> dict[str, str]:
    records: dict[str, str] = {}
    for path in sorted(repo.glob(_RECORD_GLOB)):
        if not path.is_file():
            continue
        rel = path.relative_to(repo).as_posix()
        records[rel] = path.read_text(encoding="utf-8")
    return records


def render_index(records: dict[str, str]) -> str:
    """The full `docs/amends-index.md` content, deterministic from
    `records` (path -> content) alone -- no filesystem access beyond
    what the caller already loaded, matching `amends.py`'s own
    tree-content-only contract."""
    verdict = amends.resolve_amendments(records)

    rows = []
    for target in sorted(verdict["amended"]):
        for anchor in sorted(verdict["amended"][target]):
            corrector = verdict["amended"][target][anchor]
            reason = amends.extract_reason(records[corrector])
            rows.append(f"| `{target}#{anchor}` | `{corrector}` | {reason} |")
    rows_text = "\n".join(rows) if rows else "| (none) | | |"

    unresolved_lines = []
    if verdict["broken"]:
        unresolved_lines.append("- broken (dangling target): " +
                                 ", ".join(f"`{t}`" for t in verdict["broken"]))
    if verdict["missing_section"]:
        unresolved_lines.append("- missing_section (target exists, section does not): " +
                                 ", ".join(f"`{t}`" for t in verdict["missing_section"]))
    if verdict["conflicts"]:
        parts = [f"`{k}`: {', '.join(f'`{c}`' for c in v)}"
                  for k, v in sorted(verdict["conflicts"].items())]
        unresolved_lines.append("- conflicts (two+ correctors, same target#section): " +
                                 "; ".join(parts))
    if verdict["cycles"]:
        unresolved_lines.append("- cycles: " +
                                 ", ".join(f"`{c}`" for c in verdict["cycles"]))
    unresolved_text = "\n".join(unresolved_lines) if unresolved_lines else "None."

    return _HEADER.format(rows=rows_text, unresolved=unresolved_text)


def check(repo: Path) -> list[str]:
    """Blocking reasons. Empty means pass. Two independent checks, both
    run every time (not short-circuited on the first): the generated
    index must match the tree's `amends:` edges (mirrors
    `spec_index.py::check()` -- a missing index with live edges is a hard
    failure, never read as "no amendments"), AND every unambiguous
    (`amended`) edge's target must already carry its backlink -- an
    `amends:` edge that landed in the tree but whose target has no
    backlink is exactly the "unlinked amendment" this gate exists to
    refuse (`amends_backlink.missing_backlinks()`), regardless of
    whether the index itself happens to be current."""
    records = _load_records(repo)
    bad: list[str] = []

    index_path = repo / INDEX_PATH
    expected = render_index(records)
    if not index_path.exists():
        verdict = amends.resolve_amendments(records)
        if any(verdict[k] for k in ("amended", "broken", "missing_section",
                                     "conflicts", "cycles")):
            bad.append(f"{INDEX_PATH} missing, but the tree has live "
                       "`amends:` edges -- an unlinked amendment. Run "
                       "`python3 gates/amends_index.py --update`.")
        else:
            bad.append(f"{INDEX_PATH} missing -- run "
                       "`python3 gates/amends_index.py --update` to create "
                       "it (required even with zero edges, so its absence "
                       "is never silently read as \"nothing to check\").")
    else:
        actual = index_path.read_text(encoding="utf-8")
        if actual != expected:
            bad.append(f"{INDEX_PATH} is stale -- it does not match what "
                       "the tree's `amends:` edges resolve to. Run "
                       "`python3 gates/amends_index.py --update` and "
                       "commit the result in the same change.")

    for missing in amends_backlink.missing_backlinks(records):
        bad.append(
            f"unlinked amendment: {missing} has no backlink in its "
            "target's own content -- a reader who opens the target "
            "directly would miss the correction. This is a LANDING-STEP "
            "action, not something the correcting session can do itself "
            "(see amends_backlink.py's module docstring): run "
            "`python3 gates/amends_index.py --apply-backlinks` against "
            "the merged tree and commit the result."
        )

    return bad


def update(repo: Path) -> None:
    records = _load_records(repo)
    (repo / INDEX_PATH).write_text(render_index(records), encoding="utf-8")


def write_backlinks(repo: Path) -> list[str]:
    """LANDING-STEP ONLY (see `amends_backlink.py`'s module docstring for
    why): writes the computed backlink into every amended target's file
    on disk. Returns the sorted list of target paths actually changed.
    Never called by a correcting session against a foreign issue's tree
    -- this exists for the operator/orchestrator identity running it
    against the merged main tree after the correcting PR lands."""
    records = _load_records(repo)
    updated = amends_backlink.apply_backlinks(records)
    for target, content in updated.items():
        (repo / target).write_text(content, encoding="utf-8")
    return sorted(updated)


def main() -> int:
    argv = sys.argv[1:]
    do_update = "--update" in argv
    do_apply_backlinks = "--apply-backlinks" in argv
    positional = [a for a in argv
                  if a not in ("--update", "--apply-backlinks")]
    repo = Path(positional[0] if positional else ".").resolve()

    if do_apply_backlinks:
        written = write_backlinks(repo)
        if written:
            print("backlinks written to: " + ", ".join(written))
        else:
            print("no backlinks needed -- every amended target already "
                  "carries its marker")
        if not do_update:
            return 0

    if do_update:
        update(repo)
        print(f"{INDEX_PATH} regenerated")
        return 0

    bad = check(repo)
    if bad:
        print("gate blocked:")
        for b in bad:
            print(f"  - {b}")
        return 1
    print(f"ok: {INDEX_PATH} matches the tree's amends: edges, and every "
          "amended target carries its backlink")
    return 0


if __name__ == "__main__":
    sys.exit(main())
