#!/usr/bin/env python3
"""Issue #3134: the discoverability half of `amends:`.

`amends.py`'s module docstring names the decision: a required backlink
in the target is impossible (cross-issue write-set isolation), so
discoverability is delivered by a generated, cross-cutting index --
alongside the existing `docs/specs/reconciled-index.md`, same
`docs/specs/` bucket, same `gates/spec_index.py` shape -- plus a
gate that refuses to let the index go stale. An `amends:` edge present
in the tree but missing from (or misrepresented by) the checked-in
index is an "unlinked amendment": this gate's `check()` fails closed on
it, the same way `spec_index.py` fails closed on a spec doc whose
content outran its recorded hash.

  python3 gates/amends_index.py [<repo root>]              # check mode (CI)
  python3 gates/amends_index.py [<repo root>] --update      # regenerate
  exit 0 pass (or --update done) / 1 blocked
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import amends  # noqa: E402

_REASON_RE = re.compile(r"(?m)^amends:\s*\S+\s*#\s*(.*)$")

INDEX_PATH = "docs/specs/amends-index.md"
_RECORD_GLOB = "docs/issue-*/reports/**/*.md"

_HEADER = """# Amends index (generated -- issue #3134)

Every `amends:` edge in the tree, regenerated by
`python3 gates/amends_index.py --update` and checked for drift by
`python3 gates/amends_index.py` (no `--update`). This file is the
sanctioned entry point for discovering whether a record's own content
has an outstanding section-scoped correction: `amends:` never writes a
backlink into the record it corrects (cross-issue write-set isolation
forbids it -- see `amends.py`'s module docstring), so a reader who wants
to know "is anything in this record disputed" checks here, not the
record's own prose.

A target#section pair absent from this table has no outstanding
amendment recorded in the tree. `broken` / `missing_section` /
`conflicts` / `cycles` entries are edges that failed to resolve
closed -- see `amends.py::resolve_amendments()` -- and are listed so a
human can act on them; none of them counts as a live amendment.

## Amended sections

| target#section | amending record | reason |
|---|---|---|
{rows}

## Unresolved edges

{unresolved}
"""


def _load_records(repo: Path) -> dict[str, str]:
    records: dict[str, str] = {}
    for path in sorted(repo.glob(_RECORD_GLOB)):
        if not path.is_file():
            continue
        rel = path.relative_to(repo).as_posix()
        records[rel] = path.read_text(encoding="utf-8")
    return records


def _reason(content: str) -> str:
    m = _REASON_RE.search(content)
    return m.group(1).strip() if m else ""


def render_index(records: dict[str, str]) -> str:
    """The full `docs/amends-index.md` content, deterministic from
    `records` (path -> content) alone -- no filesystem access beyond
    what the caller already loaded, matching `amends.py`'s own
    tree-content-only contract."""
    verdict = amends.resolve_amendments(records)

    rows = []
    for target in sorted(verdict["amended"]):
        for anchor in sorted(verdict["amended"][target]):
            corrector = verdict["amended"][target][anchor]
            reason = _reason(records[corrector])
            rows.append(f"| `{target}#{anchor}` | `{corrector}` | {reason} |")
    rows_text = "\n".join(rows) if rows else "| (none) | | |"

    unresolved_lines = []
    if verdict["broken"]:
        unresolved_lines.append("- broken (dangling target): " +
                                 ", ".join(f"`{t}`" for t in verdict["broken"]))
    if verdict["missing_section"]:
        unresolved_lines.append("- missing_section (target exists, section does not): " +
                                 ", ".join(f"`{t}`" for t in verdict["missing_section"]))
    if verdict["conflicts"]:
        parts = [f"`{k}`: {', '.join(f'`{c}`' for c in v)}"
                  for k, v in sorted(verdict["conflicts"].items())]
        unresolved_lines.append("- conflicts (two+ correctors, same target#section): " +
                                 "; ".join(parts))
    if verdict["cycles"]:
        unresolved_lines.append("- cycles: " +
                                 ", ".join(f"`{c}`" for c in verdict["cycles"]))
    unresolved_text = "\n".join(unresolved_lines) if unresolved_lines else "None."

    return _HEADER.format(rows=rows_text, unresolved=unresolved_text)


def check(repo: Path) -> list[str]:
    """Blocking reasons. Empty means pass. Mirrors `spec_index.py::check()`:
    a missing index with live `amends:` edges in the tree is a hard
    failure, not treated as "no amendments" -- an absent index that
    happens to match an empty tree still exists as a file, so this is
    never satisfied by silence."""
    index_path = repo / INDEX_PATH
    records = _load_records(repo)
    expected = render_index(records)

    if not index_path.exists():
        verdict = amends.resolve_amendments(records)
        if any(verdict[k] for k in ("amended", "broken", "missing_section",
                                     "conflicts", "cycles")):
            return [f"{INDEX_PATH} missing, but the tree has live `amends:` "
                     "edges -- an unlinked amendment. Run "
                     "`python3 gates/amends_index.py --update`."]
        return [f"{INDEX_PATH} missing -- run "
                 "`python3 gates/amends_index.py --update` to create it "
                 "(required even with zero edges, so its absence is never "
                 "silently read as \"nothing to check\")."]

    actual = index_path.read_text(encoding="utf-8")
    if actual != expected:
        return [f"{INDEX_PATH} is stale -- it does not match what the tree's "
                 "`amends:` edges resolve to. Run "
                 "`python3 gates/amends_index.py --update` and commit the "
                 "result in the same change (an amendment that lands "
                 "without regenerating this index is an unlinked "
                 "amendment)."]
    return []


def update(repo: Path) -> None:
    records = _load_records(repo)
    (repo / INDEX_PATH).write_text(render_index(records), encoding="utf-8")


def main() -> int:
    argv = sys.argv[1:]
    do_update = "--update" in argv
    positional = [a for a in argv if a != "--update"]
    repo = Path(positional[0] if positional else ".").resolve()
    if do_update:
        update(repo)
        print(f"{INDEX_PATH} regenerated")
        return 0
    bad = check(repo)
    if bad:
        print("gate blocked:")
        for b in bad:
            print(f"  - {b}")
        return 1
    print(f"ok: {INDEX_PATH} matches the tree's amends: edges")
    return 0


if __name__ == "__main__":
    sys.exit(main())
